### ISSUE TITLE
Chloroplethenkarten für Schulaktivitäten implementieren

### ISSUE THREAD

**Issue by knutator2** [Datenschule/datenspaziergang-app#11]

**Comment by lislis** [comment]
Nach dem Tutorial https://www.mapbox.com/help/choropleth-studio-gl-pt-1/ hab ich mal map style `DS chloropleth berlin bezierke` in unserem mapbox editor angelegt

**Comment by lislis** [comment]
Frage zum Schulaktivitätendatensatz: Nach was soll genau gefärbt werden? Nach Anzahl der `uniq` Aktivitäten pro Bezirk? Und dann noch ein extra Filter für Kategorie der Aktivität?

**Comment by lislis** [comment]
Hab das im PR nochmal geändert und ziehe das geojson direkt in `mgl-layer` hinein.
Jetzt muss das "nur noch" :tm:  mit den tatsächlichen Daten kombiniert werden.

**Comment by knutator2** [comment]
jop super, bin da auch grad dran
