### ISSUE TITLE
Point to Point

### ISSUE THREAD

**Issue by knutator2** [Datenschule/datenspaziergang-app#29]
- [x] keine Linie vom aktuellen Standpunkt zum  
- [x] Kurslinie sichtbar machen
- [x]  lange Headlines verschwinden aus dem Bildschirm

**Comment by lislis** [comment]
Die langen Headlines sind ein kleiner Deal-Breaker, oft sind sie einfach zu lang um ordentlich oben auf der Box zu sitzen.
In der StoryComponent hab ich jetzt mal versucht zu lange Titel 'inline' darzustellen, so als workaround.

![screenshot-2018-4-30 datenspaziergang](https://user-images.githubusercontent.com/1006478/39436334-f639b096-4c9d-11e8-8084-c8bca0c5ddff.png)

**Comment by lislis** [comment]
Hab das jetzt auch auf die anderen Screens, bei denen lange Title Probleme gemacht haben, übertragen.
