### ISSUE TITLE
Subjects- den nächsten logischen Schritt markieren

### ISSUE THREAD

**Issue by knutator2** [Datenschule/datenspaziergang-app#33]
auf der Subjectsseite soolte der nächste logische Schritte des Spaziergangs vormarkiert sein

**Comment by lislis** [comment]
Wie meinst du das? ZB bei Kotti dann Kriminalität highlighten?

**Comment by knutator2** [comment]
ja genau, und wenn man wieder zurückkommt Barrierefreiheit

**Comment by lislis** [comment]
Brauchen wir mit der neuen Route nicht!
