### ISSUE TITLE
Wheelmap Kartenkomponente

### ISSUE THREAD

**Issue by knutator2** [Datenschule/datenspaziergang-app#5]

**Comment by lislis** [comment]
Vllt auch interessant: das redesign von wheelmap sieht viel besser aus https://wheelmap.org/beta#?lat=52.5073&lon=13.4219&zoom=17

Wheelmap API docs sind hier https://wheelmap.org/en/api/docs; filtering nach boundingbox ist möglich https://wheelmap.org/en/api/docs/resources/nodes sollen wir 'einfach' um den Kotti eine Box ziehen und die dort enthaltenen Nodes auf eine Karte packen (analog Bäume im Görli)?

**Comment by knutator2** [comment]
jep genau, klingt perfekt. Die Betaversion find ch super, weißt du ob die Assets frei verfügbar sind? Vielleicht können wir das auch einfach als iFrame einbinden, dann müssen wir da keine Sachen nachbauen
